name: complaint_app
description: Dynamic Top-K Complaint Ranking System - DAA Semester Project
 
publish_to: 'none'
version: 1.0.0+1
 
environment:
  sdk: '>=3.0.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  # HTTP requests to Flask backend
  http: ^1.2.0
 
  # Beautiful icons
  cupertino_icons: ^1.0.6
 
  # Smooth animations
  animate_do: ^3.3.4
 
  # Google Fonts
  google_fonts: ^6.2.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 
flutter:
  uses-material-design: true
  assets:
    - assets/images/